################################################
# Copyright 2019, Yahoo Inc.
# Licensed under the Apache License, Version 2.0
# See LICENSE file in project root for terms.
################################################

elide:
  modelPackage: 'example.models'
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
  subscription:
    enabled: true
    path: /subscription
  async:
    enabled: false
    threadPoolSize: 2
    maxRunTime: 65
    cleanupEnabled: true
    queryCleanupDays: 7
    defaultAsyncQueryDAO: true
    export:
      enabled: false
  aggregation-store:
    enabled: true
    default-dialect: h2
    enableMetaDataStore: false
  dynamic-config:
    path: analytics
    enabled: true

spring:
  cloud:
    refresh:
      enabled: false

  application:
    name: Elide

  profiles:
    active: "local"

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.H2Dialect'
        '[default_batch_fetch_size]': 100
        '[use_scrollable_resultset]': true
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
  datasource:
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
    enabled: true
  activemq:
    broker-url: 'vm://embedded?broker.persistent=false,useShutdownHook=false'
    in-memory: true

server:
  port: 8080

logging:
  file:
    path: /tmp

security:
  origin: "*"